sudo: required
language: csharp
branches:
  only:
  - master

services:
  - docker

script:
  - docker build -t elph/idefix .
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push elph/idefix